function trac = fttcToTrac(fttcFn,spacing)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% trac = fttcToTrac(fttcFn,spacing)
%
% Description:
%   convert the output of ImageJ FTTC plugin into a traction stress tensor
%
% Input:
%   fttcFn: full path of the file generated by FTTC
%   spacing: factor of size conversion from image used in PIV/FTTC to 
%     image used in deep learning (104, 160, or 256) 
%
% Output: traction stress tensor, in the unit of Pascals
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% set up
fttc = load(fttcFn);
fttc = fttc(:,1:4);
xdim = floor(max(fttc(:,1))/spacing)+1;
ydim = floor(max(fttc(:,2))/spacing)+1;

trac = zeros(xdim,ydim,2);
for i=1:length(fttc)
    x = floor(fttc(i,1)/spacing)+1;
    y = floor(fttc(i,2)/spacing)+1;
    y = ydim-y+1;
    trac(x,y,1) = fttc(i,3);
    trac(x,y,2) = fttc(i,4);
end
end

